# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

def fibo2sum(n):
    result = 0
    a, b = 0, 1
    count = 1
    print "A, B, Sum"
    while b < n:
        a, b = b, a+b
        print a,b,
        if b % 2 == 0:
            result += b
            print result
        else:
            print "\n",
    print "\nFinal Result:", result


if __name__ == "__main__":
    print fibo2sum(4000000)
